/**
 * SINGLE SOURCE OF TRUTH for the number of unique public AI tools.
 *
 * The number is NOT hard-coded: `public/catalog-stats.json` is generated by
 * `scripts/compute-catalog-stats.cjs`, which runs the exact same dedup logic
 * as `getDedupedTools()` in `src/lib/catalog-server.ts` over the real catalog
 * data. Re-run that script whenever catalog data changes.
 *
 * This module is intentionally tiny + client-safe (a few bytes of JSON) so it
 * can be imported by route `head()` blocks and any component, unlike
 * `catalog-server.ts` which pulls in the multi-megabyte catalog.
 */
import stats from "../../public/catalog-stats.json";

export type CatalogStats = {
  rawTotal: number;
  uniqueTotal: number;
  duplicateCandidates: number;
  rawCategories: number;
  generatedAt: string;
};

export const CATALOG_STATS = stats as CatalogStats;

/** Exact unique tool count (e.g. 96321). */
export const TOTAL_TOOLS = CATALOG_STATS.uniqueTotal;

/** Formatted exact count, e.g. "96,321". */
export const TOTAL_TOOLS_EXACT = TOTAL_TOOLS.toLocaleString("en-US");

/** Marketing-safe rounded-down label, e.g. "96,000+". */
export const TOTAL_TOOLS_LABEL = `${(Math.floor(TOTAL_TOOLS / 1000) * 1000).toLocaleString("en-US")}+`;

/** Short label, e.g. "96K+". */
export const TOTAL_TOOLS_SHORT = `${Math.floor(TOTAL_TOOLS / 1000)}K+`;
