/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifiedRouteImport } from './routes/verified'
import { Route as UniversityRouteImport } from './routes/university'
import { Route as ToolsDictionaryDotjsonRouteImport } from './routes/tools-dictionary[.]json'
import { Route as ToolsApiDotjsonRouteImport } from './routes/tools-api[.]json'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap-static[.]xml'
import { Route as SearchApiDotjsonRouteImport } from './routes/search-api[.]json'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ExclusiveApiDotjsonRouteImport } from './routes/exclusive-api[.]json'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BlogCategoriesApiDotjsonRouteImport } from './routes/blog-categories-api[.]json'
import { Route as BlogAiGenerateApiDotjsonRouteImport } from './routes/blog-ai-generate-api[.]json'
import { Route as BlogAdminApiDotjsonRouteImport } from './routes/blog-admin-api[.]json'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiNewsApiDotjsonRouteImport } from './routes/ai-news-api[.]json'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminToolsApiDotjsonRouteImport } from './routes/admin-tools-api[.]json'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingsIndexRouteImport } from './routes/rankings/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ToolSlugRouteImport } from './routes/tool/$slug'
import { Route as SitemapToolsIndexRouteImport } from './routes/sitemap-tools.$index'
import { Route as RankingsSlugRouteImport } from './routes/rankings/$slug'
import { Route as CompareSlugRouteImport } from './routes/compare/$slug'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiPublicLogoDomainRouteImport } from './routes/api/public/logo/$domain'

const VerifiedRoute = VerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityRoute = UniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDictionaryDotjsonRoute = ToolsDictionaryDotjsonRouteImport.update({
  id: '/tools-dictionary.json',
  path: '/tools-dictionary.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsApiDotjsonRoute = ToolsApiDotjsonRouteImport.update({
  id: '/tools-api.json',
  path: '/tools-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap-static.xml',
  path: '/sitemap-static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchApiDotjsonRoute = SearchApiDotjsonRouteImport.update({
  id: '/search-api.json',
  path: '/search-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusiveApiDotjsonRoute = ExclusiveApiDotjsonRouteImport.update({
  id: '/exclusive-api.json',
  path: '/exclusive-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoriesApiDotjsonRoute =
  BlogCategoriesApiDotjsonRouteImport.update({
    id: '/blog-categories-api.json',
    path: '/blog-categories-api.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAiGenerateApiDotjsonRoute =
  BlogAiGenerateApiDotjsonRouteImport.update({
    id: '/blog-ai-generate-api.json',
    path: '/blog-ai-generate-api.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAdminApiDotjsonRoute = BlogAdminApiDotjsonRouteImport.update({
  id: '/blog-admin-api.json',
  path: '/blog-admin-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiNewsApiDotjsonRoute = AiNewsApiDotjsonRouteImport.update({
  id: '/ai-news-api.json',
  path: '/ai-news-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsApiDotjsonRoute = AdminToolsApiDotjsonRouteImport.update({
  id: '/admin-tools-api.json',
  path: '/admin-tools-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSlugRoute = ToolSlugRouteImport.update({
  id: '/tool/$slug',
  path: '/tool/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapToolsIndexRoute = SitemapToolsIndexRouteImport.update({
  id: '/sitemap-tools/$index',
  path: '/sitemap-tools/$index',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsSlugRoute = RankingsSlugRouteImport.update({
  id: '/rankings/$slug',
  path: '/rankings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogoDomainRoute = ApiPublicLogoDomainRouteImport.update({
  id: '/api/public/logo/$domain',
  path: '/api/public/logo/$domain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-tools-api.json': typeof AdminToolsApiDotjsonRoute
  '/advertise': typeof AdvertiseRoute
  '/ai-news-api.json': typeof AiNewsApiDotjsonRoute
  '/auth': typeof AuthRoute
  '/blog-admin-api.json': typeof BlogAdminApiDotjsonRoute
  '/blog-ai-generate-api.json': typeof BlogAiGenerateApiDotjsonRoute
  '/blog-categories-api.json': typeof BlogCategoriesApiDotjsonRoute
  '/categories': typeof CategoriesRoute
  '/collections': typeof CollectionsRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/exclusive-api.json': typeof ExclusiveApiDotjsonRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/research': typeof ResearchRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search-api.json': typeof SearchApiDotjsonRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/tools-api.json': typeof ToolsApiDotjsonRoute
  '/tools-dictionary.json': typeof ToolsDictionaryDotjsonRoute
  '/university': typeof UniversityRoute
  '/verified': typeof VerifiedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/rankings/$slug': typeof RankingsSlugRoute
  '/sitemap-tools/$index': typeof SitemapToolsIndexRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/api/public/logo/$domain': typeof ApiPublicLogoDomainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-tools-api.json': typeof AdminToolsApiDotjsonRoute
  '/advertise': typeof AdvertiseRoute
  '/ai-news-api.json': typeof AiNewsApiDotjsonRoute
  '/auth': typeof AuthRoute
  '/blog-admin-api.json': typeof BlogAdminApiDotjsonRoute
  '/blog-ai-generate-api.json': typeof BlogAiGenerateApiDotjsonRoute
  '/blog-categories-api.json': typeof BlogCategoriesApiDotjsonRoute
  '/categories': typeof CategoriesRoute
  '/collections': typeof CollectionsRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/exclusive-api.json': typeof ExclusiveApiDotjsonRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/research': typeof ResearchRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search-api.json': typeof SearchApiDotjsonRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/tools-api.json': typeof ToolsApiDotjsonRoute
  '/tools-dictionary.json': typeof ToolsDictionaryDotjsonRoute
  '/university': typeof UniversityRoute
  '/verified': typeof VerifiedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/rankings/$slug': typeof RankingsSlugRoute
  '/sitemap-tools/$index': typeof SitemapToolsIndexRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/blog': typeof BlogIndexRoute
  '/compare': typeof CompareIndexRoute
  '/rankings': typeof RankingsIndexRoute
  '/api/public/logo/$domain': typeof ApiPublicLogoDomainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-tools-api.json': typeof AdminToolsApiDotjsonRoute
  '/advertise': typeof AdvertiseRoute
  '/ai-news-api.json': typeof AiNewsApiDotjsonRoute
  '/auth': typeof AuthRoute
  '/blog-admin-api.json': typeof BlogAdminApiDotjsonRoute
  '/blog-ai-generate-api.json': typeof BlogAiGenerateApiDotjsonRoute
  '/blog-categories-api.json': typeof BlogCategoriesApiDotjsonRoute
  '/categories': typeof CategoriesRoute
  '/collections': typeof CollectionsRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/exclusive-api.json': typeof ExclusiveApiDotjsonRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/research': typeof ResearchRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search-api.json': typeof SearchApiDotjsonRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/tools-api.json': typeof ToolsApiDotjsonRoute
  '/tools-dictionary.json': typeof ToolsDictionaryDotjsonRoute
  '/university': typeof UniversityRoute
  '/verified': typeof VerifiedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/rankings/$slug': typeof RankingsSlugRoute
  '/sitemap-tools/$index': typeof SitemapToolsIndexRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/rankings/': typeof RankingsIndexRoute
  '/api/public/logo/$domain': typeof ApiPublicLogoDomainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-tools-api.json'
    | '/advertise'
    | '/ai-news-api.json'
    | '/auth'
    | '/blog-admin-api.json'
    | '/blog-ai-generate-api.json'
    | '/blog-categories-api.json'
    | '/categories'
    | '/collections'
    | '/companies'
    | '/contact'
    | '/exclusive-api.json'
    | '/models'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/ranking'
    | '/research'
    | '/rss.xml'
    | '/search-api.json'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/submit'
    | '/terms'
    | '/tools-api.json'
    | '/tools-dictionary.json'
    | '/university'
    | '/verified'
    | '/blog/$slug'
    | '/category/$slug'
    | '/compare/$slug'
    | '/rankings/$slug'
    | '/sitemap-tools/$index'
    | '/tool/$slug'
    | '/blog/'
    | '/compare/'
    | '/rankings/'
    | '/api/public/logo/$domain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-tools-api.json'
    | '/advertise'
    | '/ai-news-api.json'
    | '/auth'
    | '/blog-admin-api.json'
    | '/blog-ai-generate-api.json'
    | '/blog-categories-api.json'
    | '/categories'
    | '/collections'
    | '/companies'
    | '/contact'
    | '/exclusive-api.json'
    | '/models'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/ranking'
    | '/research'
    | '/rss.xml'
    | '/search-api.json'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/submit'
    | '/terms'
    | '/tools-api.json'
    | '/tools-dictionary.json'
    | '/university'
    | '/verified'
    | '/blog/$slug'
    | '/category/$slug'
    | '/compare/$slug'
    | '/rankings/$slug'
    | '/sitemap-tools/$index'
    | '/tool/$slug'
    | '/blog'
    | '/compare'
    | '/rankings'
    | '/api/public/logo/$domain'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-tools-api.json'
    | '/advertise'
    | '/ai-news-api.json'
    | '/auth'
    | '/blog-admin-api.json'
    | '/blog-ai-generate-api.json'
    | '/blog-categories-api.json'
    | '/categories'
    | '/collections'
    | '/companies'
    | '/contact'
    | '/exclusive-api.json'
    | '/models'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/ranking'
    | '/research'
    | '/rss.xml'
    | '/search-api.json'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/submit'
    | '/terms'
    | '/tools-api.json'
    | '/tools-dictionary.json'
    | '/university'
    | '/verified'
    | '/blog/$slug'
    | '/category/$slug'
    | '/compare/$slug'
    | '/rankings/$slug'
    | '/sitemap-tools/$index'
    | '/tool/$slug'
    | '/blog/'
    | '/compare/'
    | '/rankings/'
    | '/api/public/logo/$domain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminToolsApiDotjsonRoute: typeof AdminToolsApiDotjsonRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AiNewsApiDotjsonRoute: typeof AiNewsApiDotjsonRoute
  AuthRoute: typeof AuthRoute
  BlogAdminApiDotjsonRoute: typeof BlogAdminApiDotjsonRoute
  BlogAiGenerateApiDotjsonRoute: typeof BlogAiGenerateApiDotjsonRoute
  BlogCategoriesApiDotjsonRoute: typeof BlogCategoriesApiDotjsonRoute
  CategoriesRoute: typeof CategoriesRoute
  CollectionsRoute: typeof CollectionsRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  ExclusiveApiDotjsonRoute: typeof ExclusiveApiDotjsonRoute
  ModelsRoute: typeof ModelsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  ResearchRoute: typeof ResearchRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SearchApiDotjsonRoute: typeof SearchApiDotjsonRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  ToolsApiDotjsonRoute: typeof ToolsApiDotjsonRoute
  ToolsDictionaryDotjsonRoute: typeof ToolsDictionaryDotjsonRoute
  UniversityRoute: typeof UniversityRoute
  VerifiedRoute: typeof VerifiedRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CompareSlugRoute: typeof CompareSlugRoute
  RankingsSlugRoute: typeof RankingsSlugRoute
  SitemapToolsIndexRoute: typeof SitemapToolsIndexRoute
  ToolSlugRoute: typeof ToolSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  RankingsIndexRoute: typeof RankingsIndexRoute
  ApiPublicLogoDomainRoute: typeof ApiPublicLogoDomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verified': {
      id: '/verified'
      path: '/verified'
      fullPath: '/verified'
      preLoaderRoute: typeof VerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university': {
      id: '/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof UniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools-dictionary.json': {
      id: '/tools-dictionary.json'
      path: '/tools-dictionary.json'
      fullPath: '/tools-dictionary.json'
      preLoaderRoute: typeof ToolsDictionaryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools-api.json': {
      id: '/tools-api.json'
      path: '/tools-api.json'
      fullPath: '/tools-api.json'
      preLoaderRoute: typeof ToolsApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-static.xml': {
      id: '/sitemap-static.xml'
      path: '/sitemap-static.xml'
      fullPath: '/sitemap-static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-api.json': {
      id: '/search-api.json'
      path: '/search-api.json'
      fullPath: '/search-api.json'
      preLoaderRoute: typeof SearchApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusive-api.json': {
      id: '/exclusive-api.json'
      path: '/exclusive-api.json'
      fullPath: '/exclusive-api.json'
      preLoaderRoute: typeof ExclusiveApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-categories-api.json': {
      id: '/blog-categories-api.json'
      path: '/blog-categories-api.json'
      fullPath: '/blog-categories-api.json'
      preLoaderRoute: typeof BlogCategoriesApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-ai-generate-api.json': {
      id: '/blog-ai-generate-api.json'
      path: '/blog-ai-generate-api.json'
      fullPath: '/blog-ai-generate-api.json'
      preLoaderRoute: typeof BlogAiGenerateApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-admin-api.json': {
      id: '/blog-admin-api.json'
      path: '/blog-admin-api.json'
      fullPath: '/blog-admin-api.json'
      preLoaderRoute: typeof BlogAdminApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-news-api.json': {
      id: '/ai-news-api.json'
      path: '/ai-news-api.json'
      fullPath: '/ai-news-api.json'
      preLoaderRoute: typeof AiNewsApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-tools-api.json': {
      id: '/admin-tools-api.json'
      path: '/admin-tools-api.json'
      fullPath: '/admin-tools-api.json'
      preLoaderRoute: typeof AdminToolsApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/': {
      id: '/rankings/'
      path: '/rankings'
      fullPath: '/rankings/'
      preLoaderRoute: typeof RankingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$slug': {
      id: '/tool/$slug'
      path: '/tool/$slug'
      fullPath: '/tool/$slug'
      preLoaderRoute: typeof ToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-tools/$index': {
      id: '/sitemap-tools/$index'
      path: '/sitemap-tools/$index'
      fullPath: '/sitemap-tools/$index'
      preLoaderRoute: typeof SitemapToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/$slug': {
      id: '/rankings/$slug'
      path: '/rankings/$slug'
      fullPath: '/rankings/$slug'
      preLoaderRoute: typeof RankingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/logo/$domain': {
      id: '/api/public/logo/$domain'
      path: '/api/public/logo/$domain'
      fullPath: '/api/public/logo/$domain'
      preLoaderRoute: typeof ApiPublicLogoDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminToolsApiDotjsonRoute: AdminToolsApiDotjsonRoute,
  AdvertiseRoute: AdvertiseRoute,
  AiNewsApiDotjsonRoute: AiNewsApiDotjsonRoute,
  AuthRoute: AuthRoute,
  BlogAdminApiDotjsonRoute: BlogAdminApiDotjsonRoute,
  BlogAiGenerateApiDotjsonRoute: BlogAiGenerateApiDotjsonRoute,
  BlogCategoriesApiDotjsonRoute: BlogCategoriesApiDotjsonRoute,
  CategoriesRoute: CategoriesRoute,
  CollectionsRoute: CollectionsRoute,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  ExclusiveApiDotjsonRoute: ExclusiveApiDotjsonRoute,
  ModelsRoute: ModelsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  ResearchRoute: ResearchRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SearchApiDotjsonRoute: SearchApiDotjsonRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  ToolsApiDotjsonRoute: ToolsApiDotjsonRoute,
  ToolsDictionaryDotjsonRoute: ToolsDictionaryDotjsonRoute,
  UniversityRoute: UniversityRoute,
  VerifiedRoute: VerifiedRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  CompareSlugRoute: CompareSlugRoute,
  RankingsSlugRoute: RankingsSlugRoute,
  SitemapToolsIndexRoute: SitemapToolsIndexRoute,
  ToolSlugRoute: ToolSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  RankingsIndexRoute: RankingsIndexRoute,
  ApiPublicLogoDomainRoute: ApiPublicLogoDomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
