/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversityRouteImport } from './routes/university'
import { Route as ToolsDictionaryDotjsonRouteImport } from './routes/tools-dictionary[.]json'
import { Route as ToolsApiDotjsonRouteImport } from './routes/tools-api[.]json'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap-static[.]xml'
import { Route as SearchApiDotjsonRouteImport } from './routes/search-api[.]json'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ExclusiveApiDotjsonRouteImport } from './routes/exclusive-api[.]json'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiNewsApiDotjsonRouteImport } from './routes/ai-news-api[.]json'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolSlugRouteImport } from './routes/tool/$slug'
import { Route as SitemapToolsIndexRouteImport } from './routes/sitemap-tools.$index'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'

const UniversityRoute = UniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDictionaryDotjsonRoute = ToolsDictionaryDotjsonRouteImport.update({
  id: '/tools-dictionary.json',
  path: '/tools-dictionary.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsApiDotjsonRoute = ToolsApiDotjsonRouteImport.update({
  id: '/tools-api.json',
  path: '/tools-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap-static.xml',
  path: '/sitemap-static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchApiDotjsonRoute = SearchApiDotjsonRouteImport.update({
  id: '/search-api.json',
  path: '/search-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusiveApiDotjsonRoute = ExclusiveApiDotjsonRouteImport.update({
  id: '/exclusive-api.json',
  path: '/exclusive-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiNewsApiDotjsonRoute = AiNewsApiDotjsonRouteImport.update({
  id: '/ai-news-api.json',
  path: '/ai-news-api.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSlugRoute = ToolSlugRouteImport.update({
  id: '/tool/$slug',
  path: '/tool/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapToolsIndexRoute = SitemapToolsIndexRouteImport.update({
  id: '/sitemap-tools/$index',
  path: '/sitemap-tools/$index',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advertise': typeof AdvertiseRoute
  '/ai-news-api.json': typeof AiNewsApiDotjsonRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/exclusive-api.json': typeof ExclusiveApiDotjsonRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/search-api.json': typeof SearchApiDotjsonRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/tools-api.json': typeof ToolsApiDotjsonRoute
  '/tools-dictionary.json': typeof ToolsDictionaryDotjsonRoute
  '/university': typeof UniversityRoute
  '/category/$slug': typeof CategorySlugRoute
  '/sitemap-tools/$index': typeof SitemapToolsIndexRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advertise': typeof AdvertiseRoute
  '/ai-news-api.json': typeof AiNewsApiDotjsonRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/exclusive-api.json': typeof ExclusiveApiDotjsonRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/search-api.json': typeof SearchApiDotjsonRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/tools-api.json': typeof ToolsApiDotjsonRoute
  '/tools-dictionary.json': typeof ToolsDictionaryDotjsonRoute
  '/university': typeof UniversityRoute
  '/category/$slug': typeof CategorySlugRoute
  '/sitemap-tools/$index': typeof SitemapToolsIndexRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advertise': typeof AdvertiseRoute
  '/ai-news-api.json': typeof AiNewsApiDotjsonRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/exclusive-api.json': typeof ExclusiveApiDotjsonRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/search-api.json': typeof SearchApiDotjsonRoute
  '/sitemap-static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/tools-api.json': typeof ToolsApiDotjsonRoute
  '/tools-dictionary.json': typeof ToolsDictionaryDotjsonRoute
  '/university': typeof UniversityRoute
  '/category/$slug': typeof CategorySlugRoute
  '/sitemap-tools/$index': typeof SitemapToolsIndexRoute
  '/tool/$slug': typeof ToolSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/ai-news-api.json'
    | '/auth'
    | '/compare'
    | '/exclusive-api.json'
    | '/privacy'
    | '/profile'
    | '/ranking'
    | '/search-api.json'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/submit'
    | '/terms'
    | '/tools-api.json'
    | '/tools-dictionary.json'
    | '/university'
    | '/category/$slug'
    | '/sitemap-tools/$index'
    | '/tool/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/ai-news-api.json'
    | '/auth'
    | '/compare'
    | '/exclusive-api.json'
    | '/privacy'
    | '/profile'
    | '/ranking'
    | '/search-api.json'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/submit'
    | '/terms'
    | '/tools-api.json'
    | '/tools-dictionary.json'
    | '/university'
    | '/category/$slug'
    | '/sitemap-tools/$index'
    | '/tool/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/ai-news-api.json'
    | '/auth'
    | '/compare'
    | '/exclusive-api.json'
    | '/privacy'
    | '/profile'
    | '/ranking'
    | '/search-api.json'
    | '/sitemap-static.xml'
    | '/sitemap.xml'
    | '/submit'
    | '/terms'
    | '/tools-api.json'
    | '/tools-dictionary.json'
    | '/university'
    | '/category/$slug'
    | '/sitemap-tools/$index'
    | '/tool/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AiNewsApiDotjsonRoute: typeof AiNewsApiDotjsonRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ExclusiveApiDotjsonRoute: typeof ExclusiveApiDotjsonRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  SearchApiDotjsonRoute: typeof SearchApiDotjsonRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  ToolsApiDotjsonRoute: typeof ToolsApiDotjsonRoute
  ToolsDictionaryDotjsonRoute: typeof ToolsDictionaryDotjsonRoute
  UniversityRoute: typeof UniversityRoute
  CategorySlugRoute: typeof CategorySlugRoute
  SitemapToolsIndexRoute: typeof SitemapToolsIndexRoute
  ToolSlugRoute: typeof ToolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/university': {
      id: '/university'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof UniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools-dictionary.json': {
      id: '/tools-dictionary.json'
      path: '/tools-dictionary.json'
      fullPath: '/tools-dictionary.json'
      preLoaderRoute: typeof ToolsDictionaryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools-api.json': {
      id: '/tools-api.json'
      path: '/tools-api.json'
      fullPath: '/tools-api.json'
      preLoaderRoute: typeof ToolsApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-static.xml': {
      id: '/sitemap-static.xml'
      path: '/sitemap-static.xml'
      fullPath: '/sitemap-static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-api.json': {
      id: '/search-api.json'
      path: '/search-api.json'
      fullPath: '/search-api.json'
      preLoaderRoute: typeof SearchApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusive-api.json': {
      id: '/exclusive-api.json'
      path: '/exclusive-api.json'
      fullPath: '/exclusive-api.json'
      preLoaderRoute: typeof ExclusiveApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-news-api.json': {
      id: '/ai-news-api.json'
      path: '/ai-news-api.json'
      fullPath: '/ai-news-api.json'
      preLoaderRoute: typeof AiNewsApiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$slug': {
      id: '/tool/$slug'
      path: '/tool/$slug'
      fullPath: '/tool/$slug'
      preLoaderRoute: typeof ToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-tools/$index': {
      id: '/sitemap-tools/$index'
      path: '/sitemap-tools/$index'
      fullPath: '/sitemap-tools/$index'
      preLoaderRoute: typeof SitemapToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdvertiseRoute: AdvertiseRoute,
  AiNewsApiDotjsonRoute: AiNewsApiDotjsonRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ExclusiveApiDotjsonRoute: ExclusiveApiDotjsonRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  SearchApiDotjsonRoute: SearchApiDotjsonRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  ToolsApiDotjsonRoute: ToolsApiDotjsonRoute,
  ToolsDictionaryDotjsonRoute: ToolsDictionaryDotjsonRoute,
  UniversityRoute: UniversityRoute,
  CategorySlugRoute: CategorySlugRoute,
  SitemapToolsIndexRoute: SitemapToolsIndexRoute,
  ToolSlugRoute: ToolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
